import { CalendarEvent, UnscheduledTask } from '../types/calendar';

export const INITIAL_EVENTS: CalendarEvent[] = [
  // Monday 2026-09-28
  {
    id: 'evt-mon-1',
    title: 'Pilates & Morning Glow Routine 🎀',
    category: 'health',
    date: '2026-09-28',
    startTime: '08:00',
    endTime: '09:00',
    isCompleted: true,
    priority: 'high',
    location: 'Dreamhouse Studio',
    description: 'Reformer pilates flow, pink strawberry hydration, skin glow prep.',
    reminders: [
      { id: 'rem-mon-1a', minutesBefore: 15, label: '15m before 🌸' },
    ],
  },
  {
    id: 'evt-mon-2',
    title: 'Barbie World: Creative Direction & Moodboard 💖',
    category: 'deep_work',
    date: '2026-09-28',
    startTime: '09:15',
    endTime: '11:30',
    isCompleted: true,
    priority: 'high',
    description: 'Curate next-gen pastel palettes, 3D showroom models, and holographic texture assets.',
    subtasks: [
      { id: 'st-1', text: 'Select Pantone Barbie Pink #e0218a shades', completed: true },
      { id: 'st-2', text: 'Design sparkle particle animation guidelines', completed: true },
      { id: 'st-3', text: 'Review showroom mannequin 3D renders', completed: true },
    ],
    reminders: [
      { id: 'rem-mon-2a', minutesBefore: 10, label: '10m before 🎀' },
    ],
  },
  {
    id: 'evt-mon-3',
    title: 'Executive Board Sync & Sprint Strategy 👑',
    category: 'meetings',
    date: '2026-09-28',
    startTime: '11:45',
    endTime: '12:30',
    isCompleted: true,
    priority: 'high',
    location: 'Pink Ballroom / Google Meet',
    meetingUrl: 'https://meet.google.com/barbie-exec-sync',
    description: 'Align on Q4 collection launches, Dreamhouse flagship store expansions, and brand partnerships.',
    reminders: [
      { id: 'rem-mon-3a', minutesBefore: 15, label: '15m before 💖' },
      { id: 'rem-mon-3b', minutesBefore: 5, label: '5m before 🌸' },
    ],
  },
  {
    id: 'evt-mon-4',
    title: 'Pink Latte & Gourmet Lunch with Ken 🌸',
    category: 'personal',
    date: '2026-09-28',
    startTime: '12:30',
    endTime: '13:30',
    isCompleted: true,
    priority: 'low',
    location: 'Café de Barbie',
    description: 'Rose petal iced latte, avocado tartine, catch-up on weekend plans.',
  },
  {
    id: 'evt-mon-5',
    title: 'Fashion Design: Met Gala Custom Gown Specs ✨',
    category: 'deep_work',
    date: '2026-09-28',
    startTime: '14:00',
    endTime: '16:00',
    isCompleted: false,
    priority: 'high',
    description: 'Finalize hand-stitched sequin patterns and silk chiffon drape dimensions.',
    subtasks: [
      { id: 'st-4', text: 'Approve Swarovski rhinestone density map', completed: true },
      { id: 'st-5', text: 'Test corsetry flex boning comfort', completed: false },
    ],
    reminders: [
      { id: 'rem-mon-5a', minutesBefore: 15, label: '15m before 💖' },
    ],
  },
  {
    id: 'evt-mon-6',
    title: 'Dreamhouse Interior Architect Review 🎀',
    category: 'meetings',
    date: '2026-09-28',
    startTime: '16:15',
    endTime: '17:00',
    isCompleted: false,
    priority: 'medium',
    location: 'Design Suite 4',
    description: 'Review spiral slide blueprint into infinity pool and rooftop solar layout.',
    reminders: [
      { id: 'rem-mon-6a', minutesBefore: 10, label: '10m before 🎀' },
    ],
  },
  {
    id: 'evt-mon-7',
    title: 'Boss Babe Inbox Zero & Day Close 💅',
    category: 'admin',
    date: '2026-09-28',
    startTime: '17:15',
    endTime: '17:45',
    isCompleted: false,
    priority: 'low',
    description: 'Clear pending collaborator DMs, sign brand endorsements, review tomorrow’s glam schedule.',
  },
  {
    id: 'evt-mon-8',
    title: 'Sunset Malibu Rollerblade & Smoothie 🌴',
    category: 'health',
    date: '2026-09-28',
    startTime: '18:15',
    endTime: '19:15',
    isCompleted: false,
    priority: 'medium',
    location: 'Malibu Boardwalk',
    description: 'Yellow neon skates, ocean breeze, fresh dragonfruit pitaya smoothie.',
  },

  // Tuesday 2026-09-29
  {
    id: 'evt-tue-1',
    title: 'Barbie Glow Pilates & Green Matcha 🍵',
    category: 'health',
    date: '2026-09-29',
    startTime: '08:00',
    endTime: '08:45',
    isCompleted: false,
    priority: 'medium',
    location: 'Garden Terrace',
  },
  {
    id: 'evt-tue-2',
    title: 'Deep Focus: Barbie Beauty Brand Formula R&D 💖',
    category: 'deep_work',
    date: '2026-09-29',
    startTime: '09:00',
    endTime: '11:30',
    isCompleted: false,
    priority: 'high',
    description: 'Review clean shimmer lip oil viscosity and cruelty-free rose pigment batches.',
    subtasks: [
      { id: 'st-6', text: 'Benchmark hydration retention over 8 hours', completed: false },
      { id: 'st-7', text: 'Approve heart-shaped glass wand applicator', completed: false },
    ],
    reminders: [
      { id: 'rem-tue-2a', minutesBefore: 15, label: '15m before 💖' },
    ],
  },
  {
    id: 'evt-tue-3',
    title: 'PR & Hollywood Red Carpet Sync 📸',
    category: 'meetings',
    date: '2026-09-29',
    startTime: '13:00',
    endTime: '14:00',
    isCompleted: false,
    priority: 'high',
    location: 'Sunset Tower Room',
    meetingUrl: 'https://meet.google.com/barbie-hollywood-pr',
    reminders: [
      { id: 'rem-tue-3a', minutesBefore: 10, label: '10m before 🎀' },
    ],
  },
  {
    id: 'evt-tue-4',
    title: 'Dreamhouse Closet Organization & Glam Catalog 👗',
    category: 'personal',
    date: '2026-09-29',
    startTime: '15:00',
    endTime: '16:30',
    isCompleted: false,
    priority: 'medium',
    description: 'Color code footwear section from magenta to pastel blush.',
  },
  {
    id: 'evt-tue-5',
    title: 'Mani-Pedi Sparkle Touch Up 💅',
    category: 'health',
    date: '2026-09-29',
    startTime: '17:00',
    endTime: '18:15',
    isCompleted: false,
    priority: 'low',
    location: 'Pink Diamond Spa',
  },

  // Wednesday 2026-09-30
  {
    id: 'evt-wed-1',
    title: 'Morning Beach Run & Sun Salutations 🌅',
    category: 'health',
    date: '2026-09-30',
    startTime: '07:30',
    endTime: '08:30',
    isCompleted: false,
    priority: 'low',
  },
  {
    id: 'evt-wed-2',
    title: 'Deep Focus: Barbie Dreamhouse App UX & UI ✨',
    category: 'deep_work',
    date: '2026-09-30',
    startTime: '09:00',
    endTime: '12:00',
    isCompleted: false,
    priority: 'high',
    description: 'Design interactive calendar widgets, pink notification toasts, and custom sticker drawer.',
    subtasks: [
      { id: 'st-8', text: 'Create animated pink ribbon milestone celebrations', completed: false },
      { id: 'st-9', text: 'Polish responsive layout for mobile & tablet', completed: false },
    ],
    reminders: [
      { id: 'rem-wed-2a', minutesBefore: 15, label: '15m before 💖' },
    ],
  },
  {
    id: 'evt-wed-3',
    title: 'Paris Fashion Week Producer Huddle 🗼',
    category: 'meetings',
    date: '2026-09-30',
    startTime: '13:30',
    endTime: '14:30',
    isCompleted: false,
    priority: 'high',
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/pfw-barbie-runway',
  },
  {
    id: 'evt-wed-4',
    title: 'Bake Pink Heart Macarons & Dreamhouse Tea 🧁',
    category: 'personal',
    date: '2026-09-30',
    startTime: '15:30',
    endTime: '17:00',
    isCompleted: false,
    priority: 'low',
    description: 'Raspberry ganache filled macarons with edible glitter dust.',
  },

  // Thursday 2026-10-01
  {
    id: 'evt-thu-1',
    title: 'Morning Barre Workout & Core Strength 🎀',
    category: 'health',
    date: '2026-10-01',
    startTime: '08:00',
    endTime: '09:00',
    isCompleted: false,
    priority: 'medium',
  },
  {
    id: 'evt-thu-2',
    title: 'Deep Focus: Barbie Foundation Mentorship Program 👑',
    category: 'deep_work',
    date: '2026-10-01',
    startTime: '09:30',
    endTime: '12:00',
    isCompleted: false,
    priority: 'high',
    description: 'Finalize STEM scholarships and creative arts grants for young girls globally.',
    reminders: [
      { id: 'rem-thu-2a', minutesBefore: 15, label: '15m before 💖' },
    ],
  },
  {
    id: 'evt-thu-3',
    title: 'Global Ambassador 1:1 Syncs 🌸',
    category: 'meetings',
    date: '2026-10-01',
    startTime: '14:00',
    endTime: '15:30',
    isCompleted: false,
    priority: 'medium',
  },
  {
    id: 'evt-thu-4',
    title: 'Shopping Trip: Beverly Hills Rodeo Drive 🛍️',
    category: 'personal',
    date: '2026-10-01',
    startTime: '16:30',
    endTime: '18:30',
    isCompleted: false,
    priority: 'low',
    location: 'Rodeo Drive, Beverly Hills',
  },

  // Friday 2026-10-02
  {
    id: 'evt-fri-1',
    title: 'Sunrise Yoga by the Infinity Pool 🧘‍♀️',
    category: 'health',
    date: '2026-10-02',
    startTime: '07:30',
    endTime: '08:30',
    isCompleted: false,
    priority: 'low',
  },
  {
    id: 'evt-fri-2',
    title: 'Weekly Wins Showcase & All-Hands Gala 💖',
    category: 'meetings',
    date: '2026-10-02',
    startTime: '10:00',
    endTime: '11:30',
    isCompleted: false,
    priority: 'high',
    location: 'Grand Ballroom',
    reminders: [
      { id: 'rem-fri-2a', minutesBefore: 15, label: '15m before 💖' },
    ],
  },
  {
    id: 'evt-fri-3',
    title: 'Dream & Plan: Next Week Goals & Vision Board ✨',
    category: 'planning',
    date: '2026-10-02',
    startTime: '13:00',
    endTime: '14:30',
    isCompleted: false,
    priority: 'high',
    description: 'Weekly reflection, time audit review, celebrate completed timeboxes.',
  },
  {
    id: 'evt-fri-4',
    title: 'Girls Night Out: Glam Dinner & Celebration 💄',
    category: 'personal',
    date: '2026-10-02',
    startTime: '19:00',
    endTime: '22:00',
    isCompleted: false,
    priority: 'high',
    location: 'Catch LA Rooftop',
    description: 'Pink carpet arrival with Barbie crew, mocktails, music, dancing.',
    reminders: [
      { id: 'rem-fri-4a', minutesBefore: 60, label: '1 hour before 👗' },
    ],
  },

  // Saturday 2026-10-03
  {
    id: 'evt-sat-1',
    title: 'Malibu Canyon Hike with Puppies 🐾',
    category: 'health',
    date: '2026-10-03',
    startTime: '09:00',
    endTime: '11:00',
    isCompleted: false,
    priority: 'medium',
    location: 'Solstice Canyon Trail',
  },
  {
    id: 'evt-sat-2',
    title: 'Farmers Market: Fresh Peonies & Strawberries 💐',
    category: 'personal',
    date: '2026-10-03',
    startTime: '11:30',
    endTime: '13:00',
    isCompleted: false,
    priority: 'low',
    location: 'Santa Monica Farmers Market',
  },
  {
    id: 'evt-sat-3',
    title: 'Creative Atelier: Watercolor & Fashion Sketches 🎨',
    category: 'deep_work',
    date: '2026-10-03',
    startTime: '14:30',
    endTime: '17:00',
    isCompleted: false,
    priority: 'medium',
    description: 'Freeform sketching, dreamy moodboard concepts, silk scarf illustrations.',
  },

  // Sunday 2026-10-04
  {
    id: 'evt-sun-1',
    title: 'Sunday Brunch & Mimosa Toast with Friends 🥂',
    category: 'personal',
    date: '2026-10-04',
    startTime: '11:00',
    endTime: '13:00',
    isCompleted: false,
    priority: 'low',
    location: 'The Polo Lounge, Beverly Hills',
  },
  {
    id: 'evt-sun-2',
    title: 'Sunday Reset: Glam Prep & Schedule Next Week 🎀',
    category: 'planning',
    date: '2026-10-04',
    startTime: '16:00',
    endTime: '17:30',
    isCompleted: false,
    priority: 'medium',
    description: 'Sheet mask, wardrobe steaming, set reminders for upcoming week.',
  },
];

export const INITIAL_TASKS: UnscheduledTask[] = [
  {
    id: 'task-1',
    title: 'Pick up fresh pink peonies from florist 💐',
    category: 'personal',
    estimatedMinutes: 30,
    priority: 'low',
    completed: false,
    reminderMinutesBefore: 15,
  },
  {
    id: 'task-2',
    title: 'Finalize Dreamhouse spiral slide specifications 🎀',
    category: 'deep_work',
    estimatedMinutes: 60,
    priority: 'high',
    completed: false,
    reminderMinutesBefore: 10,
  },
  {
    id: 'task-3',
    title: 'Order bespoke pink glitter stationery & wax seal 💌',
    category: 'admin',
    estimatedMinutes: 20,
    priority: 'low',
    completed: false,
  },
  {
    id: 'task-4',
    title: 'Book luxury spa facial & manicure glow session 💅',
    category: 'health',
    estimatedMinutes: 15,
    priority: 'medium',
    completed: false,
    reminderMinutesBefore: 30,
  },
  {
    id: 'task-5',
    title: 'Design Barbie World keynote presentation deck 👑',
    category: 'deep_work',
    estimatedMinutes: 90,
    priority: 'high',
    completed: false,
    reminderMinutesBefore: 15,
  },
  {
    id: 'task-6',
    title: 'Select pink ribbon trims for Paris Fashion Week 🌸',
    category: 'deep_work',
    estimatedMinutes: 45,
    priority: 'medium',
    completed: false,
  },
];
